databases:
  - name: monaliza-db # Cambia el nombre a tu base existente
    plan: free

services:
  - type: web
    plan: free
    name: project_name
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn  project_name.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: monaliza-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: STRIPE_SECRET_KEY
        generateValue: true
      - key: EMAIL_HOST_USER
        generateValue: true
      - key: EMAIL_HOST_PASSWORD
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
