# Generated by Django 5.1.3 on 2024-12-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0002_alter_respuesta_es_correcta_alter_respuesta_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='texto',
            field=models.CharField(max_length=255),
        ),
    ]
