# Generated by Django 5.1.3 on 2024-12-02 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del PDF (lectura o material del curso)', max_length=255)),
                ('archivo', models.FileField(help_text='Sube el archivo PDF', upload_to='pdfs/')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='cursos.curso')),
            ],
        ),
    ]
