# Generated by Django 5.1.3 on 2024-12-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='archivo',
            field=models.FileField(help_text='Sube el archivo PDF a Cloudinary', upload_to='pdfs/'),
        ),
    ]
