# Generated by Django 5.1.3 on 2024-11-30 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_id', models.CharField(max_length=100, verbose_name='ID de Pago en Stripe')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('status', models.CharField(default='pending', max_length=50, verbose_name='Estado del Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cursos.curso', verbose_name='Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
